namespace SpriteKind {
    export const cloud = SpriteKind.create()
    export const landingpad = SpriteKind.create()
    export const plant = SpriteKind.create()
    export const bomb = SpriteKind.create()
    export const BossType = SpriteKind.create()
}
controller.left.onEvent(ControllerButtonEvent.Pressed, function () {
    shark.setImage(img`
        .............ccfff..............
        ............cddbbf..............
        ...........cddbbf...............
        ..........fccbbcf............ccc
        ....ffffffccccccff.........ccbbc
        ..ffbbbbbbbbbbbbbcfff.....cdbbc.
        ffbbbbbbbbbcbcbbbbcccff..cddbbf.
        fbcbbbbbffbbcbcbbbcccccfffdbbf..
        fbbb1111ff1bcbcbbbcccccccbbbcf..
        .fb11111111bbbbbbcccccccccbccf..
        ..fccc33cc11bbbbccccccccfffbbcf.
        ...fc131c111bbbcccccbdbc...fbbf.
        ....f33c111cbbbfdddddcc.....fbbf
        .....ff1111fbdbbfddcc........fff
        .......cccccfbdbbfc.............
        .............fffff..............
        `)
    direction = 1
})
function clearScreen () {
    fish.destroy()
    seamine.destroy()
}
info.onCountdownEnd(function () {
    if (level == 1) {
        shark.setPosition(scene.screenWidth() / 2, scene.screenHeight() / 2)
        game.splash("Level 2:")
        info.startCountdown(10)
        level += 1
        clearScreen()
        velocity1 = -120
        velocity2 = 120
    } else {
        level += 1
        clearScreen()
        game.splash("level 3: Boss")
        shark.setPosition(scene.screenWidth() / 2, scene.screenHeight() / 2)
    }
})
controller.right.onEvent(ControllerButtonEvent.Pressed, function () {
    direction = 0
    shark.setImage(img`
        ..............fffcc.............
        ..............fbbddc............
        ...............fbbddc...........
        ccc............fcbbccf..........
        cbbcc.........ffccccccffffff....
        .cbbdc.....fffcbbbbbbbbbbbbbff..
        .fbbddc..ffcccbbbbcbcbbbbbbbbbff
        ..fbbdfffcccccbbbcbcbbffbbbbbcbf
        ..fcbbbcccccccbbbcbcb1ff1111bbbf
        ..fccbcccccccccbbbbbb11111111bf.
        .fcbbfffccccccccbbbb11cc33cccf..
        .fbbf...cbdbcccccbbb111c131cf...
        fbbf.....ccdddddfbbbc111c33f....
        fff........ccddfbbdbf1111ff.....
        .............cfbbdbfccccc.......
        ..............fffff.............
        `)
})
info.onLifeZero(function () {
    shark.setVelocity(0, 0)
    seamine.setVelocity(0, 0)
    pause(100)
    if (direction == 1) {
        animation.runImageAnimation(
        shark,
        [img`
            .............ccfff..............
            ............cddbbf..............
            ...........cddbbf...............
            ..........fccbbcf............ccc
            ....ffffffccccccff.........ccbbc
            ..ffbbbbbbbbbbbbbcfff.....cdbbc.
            ffbbbbbbbbbcbcbbbbcccff..cddbbf.
            fbcbbbbb22bbcbcbbbcccccfffdbbf..
            fbbb1111221bcbcbbbcccccccbbbcf..
            .fb11111111bbbbbbcccccccccbccf..
            ..fccccccc11bbbbccccccccfffbbcf.
            ...fc131c111bbbcccccbdbc...fbbf.
            ....f33c111cbbbfdddddcc.....fbbf
            ....33f1111fbdbbfddcc........fff
            ....3..cccccfbdbbfc.............
            .............fffff..............
            ................................
            ................................
            `],
        25,
        false
        )
    } else {
        animation.runImageAnimation(
        shark,
        [img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbb22bbbbbcbf
            ..fcbbbcccccccbbbcbcb1221111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cccccccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111f33....
            .............cfbbdbfccccc..3....
            ..............fffff.............
            ................................
            ................................
            `],
        25,
        false
        )
    }
    animation.runImageAnimation(
    seamine,
    [img`
        . . . f . . . . 2 . . . 
        . . . . f f f . . . . . 
        2 2 . f f f f f . . . f 
        . . f 2 f f f 2 f . . . 
        . f f f 2 f 2 f f f . . 
        . f f f f 2 f f f f . . 
        . f f f 2 f 2 f f f . f 
        . . f 2 f f f 2 f . . . 
        2 . . f f f f f . . . . 
        . . . . f f f . . . . . 
        . . . . . . . . . 2 . . 
        . . f . . . . . . . . . 
        `,img`
        . . . f . . . . 2 . . . 
        . . . . f . . . . f . . 
        2 2 . f f f f . f . 2 f 
        f . . 2 f f f . . . . . 
        . . f f 2 f 2 f f . . . 
        . f f f f 2 f f f . . . 
        . . f f 2 f 2 f f f . f 
        . . f 2 f f f 2 f . . . 
        2 . . f f f f f . . . . 
        . 2 . . . . f . . . 2 . 
        f . . f . . . . . 2 . . 
        . . f . . f . . f . . . 
        `],
    50,
    false
    )
    pause(100)
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    fish.setVelocity(0, 0)
    info.changeScoreBy(1)
    otherSprite.destroy(effects.ashes, 10)
    if (direction == 1) {
        animation.runImageAnimation(
        shark,
        [img`
            .............ccfff..................
            ............cddbbf..................
            ...........cddbbf...................
            ..........fccbbcf............ccc....
            ....ffffffccccccff.........ccbbc....
            ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
            ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
            fbcbbbbbffbbcbcbbbcccccfffdbbf......
            fbbb1111ff1bcbcbbbcccccccbbbcf......
            .fb11111111bbbbbbcccccccccbccf......
            ..fccc33cc11bbbbccccccccfffbbcf.....
            ...fc131c111bbbcccccbdbc...fbbf.....
            ....f33c111cbbbfdddddcc.....fbbf....
            .....ff1111fbdbbfddcc........fff....
            .......cccccfbdbbfc.................
            .............fffff..................
            `,img`
            .............ccfff..................
            ............cddbbf..................
            ...........cddbbf...................
            .....ffffffccbbcf...................
            ..fffbbbbbbbbcccff..................
            .fbbbbbbbbbbbbbbbcfff......ccccc....
            .bcbbbbbffbcbcbbbbcccff...cdbbbc....
            fbbb1111ffbbcbcbbbcccccffcddbbc.....
            .fb11111111bcbcbbbcccccccbdbbf......
            ..fccc33c11bbbbbbcccccccccbbcf......
            ...fc131cc11bbbbccccccccffbccf......
            ....f33c1111bbbcccccbdbc..fbbcf.....
            .....ff1111cbbbfdddddcc....fbbf.....
            .......ccc1fbdbbfddcc.......fbbf....
            ..........ccfbdbbfc..........fff....
            .............fffff..................
            `,img`
            ...........ccfff....................
            ..........cddbbf....................
            .fffffffffddbbf.....................
            fbbbbbbbbbfcbcf.....................
            fbbc111bffbbccffff..................
            fb111111ffbbbbbcccff....ccccc.......
            .f1cc3311bbcbcbbccccf..cdbbbc.......
            .fcc131c1bbbcbcbcccccfcddbbc........
            ..f111111bbbcbcbccccccbdbbf.........
            ..f1111111bbbbbccccccccbbcf.........
            ...f111111bbbbcccccccffbccf.........
            ....c1111cbbbcccccbdbc.fbbcf........
            .....cc11cbbbfddddddc...fbbf........
            .......cffbdbbfdddcc.....fbbf.......
            ..........fbdbbfcc........fff.......
            ...........fffff....................
            `,img`
            ...........ccfff....................
            .fffffffffcbbbbf....................
            fbbbbbbbbbfffbf.....................
            fbb111bffbbbbff.....................
            fb11111ffbbbbbcff...................
            f1cccc11bbcbcbcccf..................
            .fc1c1c1bbbcbcbcccf...ccccc.........
            ...c3331bbbcbcbccccfccddbbc.........
            ..c333c1bbbbbbbcccccbddbcc..........
            ..c331c11bbbbbcccccccbbcc...........
            .cc13c111bbbbccccccffbccf...........
            .c111111cbbbcccccbbc.fccf...........
            ..cc1111cbbbfdddddc..fbbcf..........
            ....cccffbdbbfdddc....fbbf..........
            .........fbdbbfcc......fbbf.........
            ..........fffff.........fff.........
            `,img`
            .fffffff...ccfff....................
            fbbbbbbbffcbbbbf....................
            fbb111bbbbbffbf.....................
            fb11111ffbbbbff.....................
            f1cccc1ffbbbbbcff...................
            ffc1c1c1bbcbcbcccf..................
            .fcc3331bbbcbcbcccf..ccccc..........
            ..c333c1bbbcbcbccccfcddbbc..........
            ..c333c1bbbbbbbcccccddbcc...........
            ..c333c11bbbbbccccccbbcc............
            .cc331c11bbbbccccccfbccf............
            .cc13c11cbbbcccccbbcfccf............
            .c111111cbbbfdddddc.fbbcf...........
            ..cc1111fbdbbfdddc...fbbf...........
            ....cccfffbdbbfcc.....fbbf..........
            ..........fffff........fff..........
            `,img`
            ....................................
            ....................................
            ....................................
            ..............ccffff................
            .............cddbbbf................
            ......ffffffcddbbbf.................
            ....ffbbbbbbbbbbbbbcfff.......ccccc.
            ..ffbbbbbbbbcbcbbbbbcccff....cdbbbc.
            .fbbbbbbbbbbcbbcbbbbcccccfffcddbbc..
            fbcbbbbbbbbbbcbcbbbbccccccccbdbbf...
            fbbbbbbbfffbbcbbbbbccccccccccbbcf...
            ffbb1111fffbbcbbbbcccccccbcffbccf...
            .ff111111111bbbbccccccbbbcc..fbbcf..
            ...ccccccc111bdbbbfddbccc.....ffbbf.
            .......ccccccfbdbbbfcc..........fff.
            ..............ffffff................
            `,img`
            .............ccfff..................
            ............cddbbf..................
            ...........cddbbf...................
            ..........fccbbcf............ccc....
            ....ffffffccccccff.........ccbbc....
            ..ffbbbbbbbbbbbbbcfff.....cdbbc.....
            ffbbbbbbbbbcbcbbbbcccff..cddbbf.....
            fbcbbbbbffbbcbcbbbcccccfffdbbf......
            fbbb1111ff1bcbcbbbcccccccbbbcf......
            .fb11111111bbbbbbcccccccccbccf......
            ..fccc33cc11bbbbccccccccfffbbcf.....
            ...fc131c111bbbcccccbdbc...fbbf.....
            ....f33c111cbbbfdddddcc.....fbbf....
            .....ff1111fbdbbfddcc........fff....
            .......cccccfbdbbfc.................
            .............fffff..................
            `],
        25,
        false
        )
    } else {
        animation.runImageAnimation(
        shark,
        [img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            ................................
            ................................
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ...............fcbbccffffff.....
            ..............ffcccbbbbbbbbfff..
            ccccc......fffcbbbbbbbbbbbbbbbf.
            cbbbdc...ffcccbbbbcbcbffbbbbbcbf
            .cbbddcffcccccbbbcbcbbff1111bbbf
            ..fbbdbcccccccbbbcbcb11111111bf.
            ..fcbbcccccccccbbbbbb11c33cccf..
            ..fccbffccccccccbbbb11cc131cf...
            .fcbbf..cbdbcccccbbb1111c33f....
            .fbbf....ccdddddfbbbc1111ff.....
            fbbf.......ccddfbbdbf1ccc.......
            fff..........cfbbdbfcc..........
            ..............fffff.............
            ................................
            ................................
            `,img`
            .............fffcc..............
            .............fbbddc.............
            ..............fbbddfffffffff....
            ..............fcbcfbbbbbbbbbf...
            ...........ffffccbbffb111cbbf...
            ccccc....ffcccbbbbbff111111bf...
            cbbbdc..fccccbbcbcbb1133cc1f....
            .cbbddcfcccccbcbcbbb1c131ccf....
            ..fbbdbccccccbcbcbbb111111f.....
            ..fcbbccccccccbbbbb1111111f.....
            ..fccbffcccccccbbbb111111f......
            .fcbbf.cbdbcccccbbbc1111c.......
            .fbbf...cddddddfbbbc11cc........
            fbbf.....ccdddfbbdbffc..........
            fff........ccfbbdbf.............
            .............fffff..............
            ................................
            ................................
            `,img`
            ...........fffcc................
            ...........fbbbbcfffffffff......
            ............fbfffbbbbbbbbbf.....
            ............ffbbbbffb111bbf.....
            ..........ffcbbbbbff11111bf.....
            .........fcccbcbcbb11cccc1f.....
            ccccc...fcccbcbcbbb1c1c1cf......
            cbbddccfccccbcbcbbb1333c........
            .ccbddbcccccbbbbbbb1c333c.......
            ..ccbbcccccccbbbbb11c133c.......
            ..fccbffccccccbbbb111c31cc......
            ..fccf.cbbcccccbbbc111111c......
            .fcbbf..cdddddfbbbc1111cc.......
            .fbbf....cdddfbbdbffccc.........
            fbbf......ccfbbdbf..............
            fff.........fffff...............
            ................................
            ................................
            `,img`
            ..........fffcc...fffffff.......
            ..........fbbbbcffbbbbbbbf......
            ...........fbffbbbbb111bbf......
            ...........ffbbbbff11111bf......
            .........ffcbbbbbff1cccc1f......
            ........fcccbcbcbb1c1c1cff......
            ccccc..fcccbcbcbbb1333ccf.......
            cbbddcfccccbcbcbbb1c333c........
            .ccbddcccccbbbbbbb1c333c........
            ..ccbbccccccbbbbb11c333c........
            ..fccbfccccccbbbb11c133cc.......
            ..fccfcbbcccccbbbc11c31cc.......
            .fcbbf.cdddddfbbbc111111c.......
            .fbbf...cdddfbbdbf1111cc........
            fbbf.....ccfbbdbfffccc..........
            fff........fffff................
            ................................
            ................................
            `,img`
            ................................
            ................................
            ................................
            ...............ffffcc...........
            ...............fbbbddc..........
            ................fbbbddcffffff...
            ccccc.......fffcbbbbbbbbbbbbbff.
            cbbbdc....ffcccbbbbbcbcbbbbbbbbf
            .cbbddcfffcccccbbbbcbbcbbbbbbbbb
            ..fbbdbccccccccbbbbcbcbbbbbbbbbb
            ..fcbbccccccccccbbbbbcbbfffbbbbb
            ..fccbffcbcccccccbbbbcbbfff1111b
            .fcbbf..ccbbbccccccbbbb111111111
            fbbff.....cccbddfbbbdb111ccccccc
            fff..........ccfbbbdbfcccccc....
            ...............ffffff...........
            ................................
            ................................
            `,img`
            ..............fffcc.............
            ..............fbbddc............
            ...............fbbddc...........
            ccc............fcbbccf..........
            cbbcc.........ffccccccffffff....
            .cbbdc.....fffcbbbbbbbbbbbbbff..
            .fbbddc..ffcccbbbbcbcbbbbbbbbbff
            ..fbbdfffcccccbbbcbcbbffbbbbbcbf
            ..fcbbbcccccccbbbcbcb1ff1111bbbf
            ..fccbcccccccccbbbbbb11111111bf.
            .fcbbfffccccccccbbbb11cc33cccf..
            .fbbf...cbdbcccccbbb111c131cf...
            fbbf.....ccdddddfbbbc111c33f....
            fff........ccddfbbdbf1111ff.....
            .............cfbbdbfccccc.......
            ..............fffff.............
            ................................
            ................................
            `],
        25,
        false
        )
    }
    if (randint(1, 2) == 1) {
        shark.say("Yummy!", 300)
    } else {
        if (randint(1, 2) == 1) {
            shark.say("Tasty!", 300)
        } else {
            shark.say("MMMmmm", 300)
        }
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    seamine.destroy(effects.fire, 100)
})
let velocity2 = 0
let velocity1 = 0
let seamine: Sprite = null
let fish: Sprite = null
let direction = 0
let level = 0
let shark: Sprite = null
game.splash("Eat as many fish as possible.")
game.splash("Use the arrow keys to move.")
game.splash("Level 1:")
info.startCountdown(10)
info.setScore(0)
shark = sprites.create(img`
    .............ccfff..............
    ............cddbbf..............
    ...........cddbbf...............
    ..........fccbbcf............ccc
    ....ffffffccccccff.........ccbbc
    ..ffbbbbbbbbbbbbbcfff.....cdbbc.
    ffbbbbbbbbbcbcbbbbcccff..cddbbf.
    fbcbbbbbffbbcbcbbbcccccfffdbbf..
    fbbb1111ff1bcbcbbbcccccccbbbcf..
    .fb11111111bbbbbbcccccccccbccf..
    ..fccc33cc11bbbbccccccccfffbbcf.
    ...fc131c111bbbcccccbdbc...fbbf.
    ....f33c111cbbbfdddddcc.....fbbf
    .....ff1111fbdbbfddcc........fff
    .......cccccfbdbbfc.............
    .............fffff..............
    `, SpriteKind.Player)
shark.setStayInScreen(true)
info.setLife(3)
level = 1
game.onUpdate(function () {
    controller.moveSprite(shark)
})
game.onUpdate(function () {
	
})
game.onUpdate(function () {
	
})
game.onUpdateInterval(randint(10000, 15000), function () {
    if (level != 3) {
        seamine = sprites.create(img`
            . . . f f f . . . 
            . . f f f f f . . 
            . f 2 f f f 2 f . 
            f f f 2 f 2 f f f 
            f f f f 2 f f f f 
            f f f 2 f 2 f f f 
            . f 2 f f f 2 f . 
            . . f f f f f . . 
            . . . f f f . . . 
            `, SpriteKind.Enemy)
        if (randint(0, 1) == 0) {
            seamine.setPosition(-8, randint(15, 100))
            seamine.setVelocity(velocity2, 0)
        } else {
            seamine.setPosition(168, randint(15, 100))
            seamine.setVelocity(velocity1, 0)
        }
    } else {
        seamine.destroy()
    }
})
game.onUpdateInterval(2100, function () {
    if (level != 3) {
        if (randint(0, 1) == 0) {
            fish = sprites.create(img`
                . . . . c c c c . . . . . . . . 
                . . . c d d d d c c . . . . . . 
                . . . c d c c c c c c . . . . . 
                c c . c c d 4 4 4 4 c c . . . . 
                c 4 c c 1 4 4 4 4 4 d 4 c . . . 
                f 4 c 1 d 4 4 4 4 1 4 4 4 c . . 
                f 4 4 1 4 4 4 4 4 1 4 4 4 4 c . 
                f 4 f 1 4 4 f c 1 1 4 4 4 4 4 f 
                f 4 f 1 4 4 f 4 c 1 4 f 4 4 4 f 
                f f f d 4 4 f 4 4 1 4 4 4 4 4 f 
                . . f f d 4 4 c c 1 4 4 4 4 f . 
                . . . f c 4 4 4 4 4 d 4 f f . . 
                . . c b d c 4 4 4 4 f f . . . . 
                . . c d d d f f f f . . . . . . 
                . . . c c c . . . . . . . . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Food)
            fish.setPosition(-10, randint(15, 100))
            fish.setVelocity(velocity2, 0)
        } else {
            fish = sprites.create(img`
                . . . . . . . . c c c c . . . . 
                . . . . . . c c d d d d c . . . 
                . . . . . c c c c c c d c . . . 
                . . . . c c 4 4 4 4 d c c . c c 
                . . . c 4 d 4 4 4 4 4 1 c c 4 c 
                . . c 4 4 4 1 4 4 4 4 d 1 c 4 f 
                . c 4 4 4 4 1 4 4 4 4 4 1 4 4 f 
                f 4 4 4 4 4 1 1 c f 4 4 1 f 4 f 
                f 4 4 4 f 4 1 c 4 f 4 4 1 f 4 f 
                f 4 4 4 4 4 1 4 4 f 4 4 d f f f 
                . f 4 4 4 4 1 c c 4 4 d f f . . 
                . . f f 4 d 4 4 4 4 4 c f . . . 
                . . . . f f 4 4 4 4 c d b c . . 
                . . . . . . f f f f d d d c . . 
                . . . . . . . . . . c c c . . . 
                . . . . . . . . . . . . . . . . 
                `, SpriteKind.Food)
            fish.setPosition(170, randint(15, 100))
            fish.setVelocity(velocity1, 0)
        }
    } else {
        fish.destroy()
    }
})
game.onUpdateInterval(2100, function () {
    if (level == 1) {
        velocity1 = -90
        velocity2 = 90
    }
})
